name: Java CI with Gradle and MongoDB

permissions: write-all

on:
  push:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    timeout-minutes: 0
    permissions:
      contents: read

    services:
      mongodb:
        image: mongo:8.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ping: 1})'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@cc4fc85e6b35bafd578d5ffbc76a5518407e1af0 # v4.2.1

      - name: Install MongoDB Shell (mongosh)
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh

      - name: Wait for MongoDB to Start
        run: |
          for i in {1..10}; do
            if mongosh --host localhost --port 27017 --eval "db.runCommand({ping: 1})"; then
              echo "MongoDB is ready!";
              exit 0;
            fi;
            sleep 3;
          done;
          echo "MongoDB did not become ready in time!" && exit 1;

      - name: Create Test Database
        run: |
          mongosh --host localhost --port 27017 <<EOF
          use testdb
          db.test.insertOne({ initialized: true });
          EOF

      - name: Test with Gradle Wrapper
        run: gradle test --no-daemon --stacktrace --info

      - name: Build with Gradle Wrapper and ShadowJar
        run: gradle shadowJar

